### ISSUE TITLE
UI/UX Improvement

### ISSUE THREAD

**Issue by MarioFares** [HarvardPL/AbcDatalog#2]
First, thank you to the authors for this wonderful tool.

I think there are a lot of improvements that can be made in terms of the interface and user experience. Some little additions can bring this program a long way and make it much more convenient for students to use.

Some suggestions

- Changing the Look and Feel to [FlatLaF](https://github.com/JFormDesigner/FlatLaf). This would bring about the most difference with about 4 lines of code given the dependencies are met upon compilation. In short, this is the look and feel of JetBrains IDEs.
- Changing the font to something more readable like [JetBrains Mono](https://www.jetbrains.com/lp/mono/) 
- Adding an edit menu with standard editing controls (Undo, Redo, Cut, Copy, Paste, Select All, Clear All, etc.). Some of these could be implemented cleanly by extending JTextArea.
- Adding a view menu with at least the following (Zoom in, Zoom out, Restore default zoom). In addition, having the option to switch to a vertical view (editors are side by side rather than on top of each other)
- Parentheses completion
- Adding accelerators and mnemonics to the menus and menu items

Beyond these additions, there are a couple of line operations that could be very convenient (ones that I wish I had when completing assignments with the tool)

- Delete current line
- Duplicate current line
- Move lines up/down

I have experience with Swing and desktop development, and I am more than willing to spearhead these changes. No changes are needed to anything but the gui directory.

**Comment by MarioFares** [comment]
Thank you for the reply!

I have already implemented most features on a local copy of the repository. Just so we are on the same page, how small should the PRs be? For example, can the entire View menu be a PR with options like Zoom in, Zoom out, Default Zoom. Or should each of these menu items be their own PRs?

Just a little clarity on that point and we're good to go!

**Comment by aaronbembenek** [comment]
Great! Doing the entire View menu as one PR would be fine. If it helps give a sense of granularity, I'd say that all the improvements listed in your original message could be done through ~6 PRs: JetBrains styling, edit menu, view menu, parentheses completion, accelerators, line operations. (Don't feel the need to follow that breakdown exactly; it's just to demonstrate the rough granularity we're going for.)

**Comment by aaronbembenek** [comment]
Thanks for your great contributions!
