### ISSUE TITLE
Are there plans to release this library to the Maven repository?

### ISSUE THREAD

**Issue by eastack** [HarvardPL/AbcDatalog#23]

**Comment by aaronbembenek** [comment]
Thanks for your interest! I think this is a good idea and I'll give it a try sometime in the next few days.

**Comment by aaronbembenek** [comment]
You should now be able to find AbcDatalog on [Maven Central](https://central.sonatype.com/artifact/io.github.harvardpl/AbcDatalog).

Let use know if you run into any issues!

**Comment by eastack** [comment]
Awesome! Thank you so much for making this available on Maven Central. Really happy to start using it!
