### ISSUE TITLE
UI suggestion: overtype closing parenthesis

### ISSUE THREAD

**Issue by tmoux** [HarvardPL/AbcDatalog#8]
I have a small UI suggestion that should complement the autocompleting parentheses feature: "overtyping" closing brackets. This would allow users to type over an existing closing bracket without adding an extra bracket.
For example, when typing `edge(a, b).`, one first types `edge(`, which automatically creates the closing bracket, resulting in the text `edge()`. Without this feature, users would have to manually move their cursor around the existing closing bracket.

This is the standard behavior in text editors such as VSCode and Sublime Text ([https://stackoverflow.com/questions/75002527/how-editor-autoclosingovertype-works-in-vscode-settings](https://stackoverflow.com/questions/75002527/how-editor-autoclosingovertype-works-in-vscode-settings)).

I have a patch to implement this, and I'm happy to submit a PR. I just wanted to check whether you would welcome this change to the UI.

**Comment by aaronbembenek** [comment]
Thanks for trying AbcDatalog and being interested in contributing to it! That sounds like a great improvement and we'd definitely welcome a PR implementing it :)
